/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;


import Logica.LogicaJuego;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.Timer;





/**
 *
 * @author esteb
 */
public class JCategorias extends javax.swing.JFrame {



    /**
     * Variables animaciones paneles
     */

    private String preguntasVideojuegos = "Videojuegos";
    private String preguntasDeportes = "Deportes";
    private String preguntasMusica = "Musica";
    private String preguntasSorpresa = "Sorpresa";

    
    


    

            

 





   /**
    * Constructor
    */
    public JCategorias() {
        initComponents();
       

    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        panelDeco1 = new com.poo.triviaquirk.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        panelBtnSalir = new com.poo.triviaquirk.PanelRound();
        btnSalir = new javax.swing.JButton();
        panelContainer2 = new com.poo.triviaquirk.PanelRound();
        panelBtnJugar2 = new com.poo.triviaquirk.PanelRound();
        btnJuegos = new javax.swing.JButton();
        panelContainer3 = new com.poo.triviaquirk.PanelRound();
        panelBtnJugar3 = new com.poo.triviaquirk.PanelRound();
        btnMusica = new javax.swing.JButton();
        panelContainer4 = new com.poo.triviaquirk.PanelRound();
        panelBtnJugar4 = new com.poo.triviaquirk.PanelRound();
        btnDeportes = new javax.swing.JButton();
        panelContainer5 = new com.poo.triviaquirk.PanelRound();
        panelBtnJugar5 = new com.poo.triviaquirk.PanelRound();
        btnJugar5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trivia Quirk");
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(84, 13, 110));

        panelDeco1.setBackground(new java.awt.Color(238, 66, 102));
        panelDeco1.setRoundBottomLeft(60);
        panelDeco1.setRoundTopLeft(60);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selecciona una categoría");

        javax.swing.GroupLayout panelDeco1Layout = new javax.swing.GroupLayout(panelDeco1);
        panelDeco1.setLayout(panelDeco1Layout);
        panelDeco1Layout.setHorizontalGroup(
            panelDeco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeco1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelDeco1Layout.setVerticalGroup(
            panelDeco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        panelBtnSalir.setBackground(new java.awt.Color(255, 210, 63));
        panelBtnSalir.setRoundBottomRight(60);
        panelBtnSalir.setRoundTopRight(60);

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 0, 51));
        btnSalir.setText("Volver");
        btnSalir.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnSalirLayout = new javax.swing.GroupLayout(panelBtnSalir);
        panelBtnSalir.setLayout(panelBtnSalirLayout);
        panelBtnSalirLayout.setHorizontalGroup(
            panelBtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnSalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        panelBtnSalirLayout.setVerticalGroup(
            panelBtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnSalirLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnSalir)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelContainer2.setBackground(new java.awt.Color(238, 66, 102));
        panelContainer2.setRoundBottomLeft(60);
        panelContainer2.setRoundBottomRight(60);
        panelContainer2.setRoundTopLeft(60);
        panelContainer2.setRoundTopRight(60);

        panelBtnJugar2.setBackground(new java.awt.Color(255, 210, 63));
        panelBtnJugar2.setRoundBottomLeft(60);
        panelBtnJugar2.setRoundBottomRight(60);
        panelBtnJugar2.setRoundTopLeft(60);
        panelBtnJugar2.setRoundTopRight(60);

        btnJuegos.setBackground(new java.awt.Color(0, 0, 0));
        btnJuegos.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnJuegos.setForeground(new java.awt.Color(255, 102, 0));
        btnJuegos.setText("Juegos");
        btnJuegos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnJuegos.setContentAreaFilled(false);
        btnJuegos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnJugar2Layout = new javax.swing.GroupLayout(panelBtnJugar2);
        panelBtnJugar2.setLayout(panelBtnJugar2Layout);
        panelBtnJugar2Layout.setHorizontalGroup(
            panelBtnJugar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnJugar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBtnJugar2Layout.setVerticalGroup(
            panelBtnJugar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnJugar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelContainer2Layout = new javax.swing.GroupLayout(panelContainer2);
        panelContainer2.setLayout(panelContainer2Layout);
        panelContainer2Layout.setHorizontalGroup(
            panelContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContainer2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelBtnJugar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelContainer2Layout.setVerticalGroup(
            panelContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContainer2Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(panelBtnJugar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        panelContainer3.setBackground(new java.awt.Color(238, 66, 102));
        panelContainer3.setRoundBottomLeft(60);
        panelContainer3.setRoundBottomRight(60);
        panelContainer3.setRoundTopLeft(60);
        panelContainer3.setRoundTopRight(60);

        panelBtnJugar3.setBackground(new java.awt.Color(255, 210, 63));
        panelBtnJugar3.setRoundBottomLeft(60);
        panelBtnJugar3.setRoundBottomRight(60);
        panelBtnJugar3.setRoundTopLeft(60);
        panelBtnJugar3.setRoundTopRight(60);

        btnMusica.setBackground(new java.awt.Color(0, 0, 0));
        btnMusica.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnMusica.setForeground(new java.awt.Color(255, 102, 0));
        btnMusica.setText("Musica");
        btnMusica.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnMusica.setContentAreaFilled(false);
        btnMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnJugar3Layout = new javax.swing.GroupLayout(panelBtnJugar3);
        panelBtnJugar3.setLayout(panelBtnJugar3Layout);
        panelBtnJugar3Layout.setHorizontalGroup(
            panelBtnJugar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnJugar3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMusica, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBtnJugar3Layout.setVerticalGroup(
            panelBtnJugar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnJugar3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMusica, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelContainer3Layout = new javax.swing.GroupLayout(panelContainer3);
        panelContainer3.setLayout(panelContainer3Layout);
        panelContainer3Layout.setHorizontalGroup(
            panelContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContainer3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelBtnJugar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelContainer3Layout.setVerticalGroup(
            panelContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContainer3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBtnJugar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        panelContainer4.setBackground(new java.awt.Color(238, 66, 102));
        panelContainer4.setRoundBottomLeft(60);
        panelContainer4.setRoundBottomRight(60);
        panelContainer4.setRoundTopLeft(60);
        panelContainer4.setRoundTopRight(60);

        panelBtnJugar4.setBackground(new java.awt.Color(255, 210, 63));
        panelBtnJugar4.setRoundBottomLeft(60);
        panelBtnJugar4.setRoundBottomRight(60);
        panelBtnJugar4.setRoundTopLeft(60);
        panelBtnJugar4.setRoundTopRight(60);

        btnDeportes.setBackground(new java.awt.Color(0, 0, 0));
        btnDeportes.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnDeportes.setForeground(new java.awt.Color(255, 102, 0));
        btnDeportes.setText("Deportes");
        btnDeportes.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnDeportes.setContentAreaFilled(false);
        btnDeportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnJugar4Layout = new javax.swing.GroupLayout(panelBtnJugar4);
        panelBtnJugar4.setLayout(panelBtnJugar4Layout);
        panelBtnJugar4Layout.setHorizontalGroup(
            panelBtnJugar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnJugar4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeportes, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBtnJugar4Layout.setVerticalGroup(
            panelBtnJugar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnJugar4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeportes, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelContainer4Layout = new javax.swing.GroupLayout(panelContainer4);
        panelContainer4.setLayout(panelContainer4Layout);
        panelContainer4Layout.setHorizontalGroup(
            panelContainer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContainer4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelBtnJugar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelContainer4Layout.setVerticalGroup(
            panelContainer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContainer4Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(panelBtnJugar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        panelContainer5.setBackground(new java.awt.Color(238, 66, 102));
        panelContainer5.setRoundBottomLeft(60);
        panelContainer5.setRoundBottomRight(60);
        panelContainer5.setRoundTopLeft(60);
        panelContainer5.setRoundTopRight(60);

        panelBtnJugar5.setBackground(new java.awt.Color(255, 210, 63));
        panelBtnJugar5.setRoundBottomLeft(60);
        panelBtnJugar5.setRoundBottomRight(60);
        panelBtnJugar5.setRoundTopLeft(60);
        panelBtnJugar5.setRoundTopRight(60);

        btnJugar5.setBackground(new java.awt.Color(0, 0, 0));
        btnJugar5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnJugar5.setForeground(new java.awt.Color(255, 102, 0));
        btnJugar5.setText("Sorpresa");
        btnJugar5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnJugar5.setContentAreaFilled(false);
        btnJugar5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnJugar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnJugar5Layout = new javax.swing.GroupLayout(panelBtnJugar5);
        panelBtnJugar5.setLayout(panelBtnJugar5Layout);
        panelBtnJugar5Layout.setHorizontalGroup(
            panelBtnJugar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnJugar5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnJugar5, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBtnJugar5Layout.setVerticalGroup(
            panelBtnJugar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnJugar5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnJugar5, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelContainer5Layout = new javax.swing.GroupLayout(panelContainer5);
        panelContainer5.setLayout(panelContainer5Layout);
        panelContainer5Layout.setHorizontalGroup(
            panelContainer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContainer5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelBtnJugar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelContainer5Layout.setVerticalGroup(
            panelContainer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContainer5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBtnJugar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelDeco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(panelContainer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelContainer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelContainer5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(panelDeco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelContainer5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelContainer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(panelBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Oculta la ventana actual y activa el modo de juego de un solo jugador con preguntas de videojuegos.
 * @param evt El evento de acción que desencadena este método
 */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        Jmenu menu = new Jmenu();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed
/**
 * Oculta la ventana actual y activa el modo de juego de un solo jugador con preguntas de música.
 * @param evt El evento de acción que desencadena este método
 */
    private void btnJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegosActionPerformed
        this.setVisible(false);
        LogicaJuego logica = new LogicaJuego();
        JsinglePlayer jsinglePlayer = new JsinglePlayer();
        logica.activarSinglePlayer(preguntasVideojuegos, jsinglePlayer); 
    }//GEN-LAST:event_btnJuegosActionPerformed
/**
 * Oculta la ventana actual y activa el modo de juego de un solo jugador con preguntas de deportes.
 * @param evt El evento de acción que desencadena este método
 */
    private void btnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicaActionPerformed
        this.setVisible(false);
        LogicaJuego logica = new LogicaJuego();
        JsinglePlayer jsinglePlayer = new JsinglePlayer();
        logica.activarSinglePlayer(preguntasMusica, jsinglePlayer); 
    }//GEN-LAST:event_btnMusicaActionPerformed
/**
 * Acción ejecutada al presionar el botón relacionado con el tema de deportes en la interfaz.
 * Oculta la ventana actual, inicializa una nueva instancia de la lógica de juego y un jugador para el modo de un solo jugador.
 * Activa el modo de un solo jugador con un conjunto específico de preguntas relacionadas con deportes.
 *
 * @param evt El evento de acción que desencadena este método al hacer clic en el botón de deportes.
 */
    private void btnDeportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeportesActionPerformed
        this.setVisible(false);
        LogicaJuego logica = new LogicaJuego();
        JsinglePlayer jsinglePlayer = new JsinglePlayer();
        logica.activarSinglePlayer(preguntasDeportes, jsinglePlayer);        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeportesActionPerformed
/**
 * Acción realizada al presionar el botón "Jugar 5" en la interfaz.
 * Oculta la ventana actual, crea una nueva lógica de juego y un jugador para el modo de juego individual.
 * Activa el modo de juego de un solo jugador con un conjunto de preguntas sorpresa.
 * 
 * @param evt El evento de acción que desencadena este método al hacer clic en el botón "Jugar 5".
 */
    private void btnJugar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugar5ActionPerformed
        this.setVisible(false);   
        LogicaJuego logica = new LogicaJuego();
        JsinglePlayer jsinglePlayer = new JsinglePlayer();
        logica.activarSinglePlayer(preguntasSorpresa, jsinglePlayer); 
    }//GEN-LAST:event_btnJugar5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton btnDeportes;
    private javax.swing.JButton btnJuegos;
    private javax.swing.JButton btnJugar5;
    private javax.swing.JButton btnMusica;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private com.poo.triviaquirk.PanelRound panelBtnJugar2;
    private com.poo.triviaquirk.PanelRound panelBtnJugar3;
    private com.poo.triviaquirk.PanelRound panelBtnJugar4;
    private com.poo.triviaquirk.PanelRound panelBtnJugar5;
    private com.poo.triviaquirk.PanelRound panelBtnSalir;
    private com.poo.triviaquirk.PanelRound panelContainer2;
    private com.poo.triviaquirk.PanelRound panelContainer3;
    private com.poo.triviaquirk.PanelRound panelContainer4;
    private com.poo.triviaquirk.PanelRound panelContainer5;
    private com.poo.triviaquirk.PanelRound panelDeco1;
    // End of variables declaration//GEN-END:variables
}
