/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;


import java.awt.event.ActionEvent;
import javax.swing.Timer;
import Logica.LogicaJuego;
import com.poo.triviaquirk.PanelRound;
import java.awt.Color;
import java.awt.Font;




/**
 *
 * @author esteb
 */
public class JMultijugador extends javax.swing.JFrame {



    /**
     * Variables animaciones paneles
     */
    private final Timer animationTimer;
    private int animationX = 900;
    private Byte respuesta = 0;

    

    
    

            

 





   /**
    * Constructor
    */
    public JMultijugador() {
        this.respuesta = 0;
        initComponents();
         // Inicializa el temporizador de animación
        animationTimer = new Timer(10, (ActionEvent e) -> {
            //animatePanel1();

            
        });

        // Inicia la animación al iniciar el programa
        animationTimer.start();
        
        


    }
    
    



    /**
     * Metodo para la animación del panel 1
     */
    private void animatePanel1() {
        // Incrementa la posición X del panelDeco1
        panelContador.setLocation(animationX, panelContador.getY());

        // Detiene la animación cuando llega a la posición deseada
        if (animationX == 624) {
            animationTimer.stop();
        }

        // Incrementa la posición X en cada iteración
        animationX -= 6;
    
    }
    
    
    
    

    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        panelContador = new com.poo.triviaquirk.PanelRound();
        lbContador = new javax.swing.JLabel();
        panelPregunta = new com.poo.triviaquirk.PanelRound();
        lbPregunta = new javax.swing.JLabel();
        panelOpcion1 = new com.poo.triviaquirk.PanelRound();
        btnOpcionA = new javax.swing.JButton();
        panelPuntos = new com.poo.triviaquirk.PanelRound();
        lbPuntos = new javax.swing.JLabel();
        panelOpcion2 = new com.poo.triviaquirk.PanelRound();
        btnOpcionB = new javax.swing.JButton();
        panelOpcion3 = new com.poo.triviaquirk.PanelRound();
        btnOpcionC = new javax.swing.JButton();
        panelCategoria = new com.poo.triviaquirk.PanelRound();
        lbCategoria = new javax.swing.JLabel();
        panelBtnSalir = new com.poo.triviaquirk.PanelRound();
        lbJugadorActual = new javax.swing.JLabel();
        panelBtnSalir1 = new com.poo.triviaquirk.PanelRound();
        btnSalir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trivia Quirk");
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(84, 13, 110));

        panelContador.setBackground(new java.awt.Color(238, 66, 102));
        panelContador.setRoundBottomLeft(60);
        panelContador.setRoundTopLeft(60);

        lbContador.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        lbContador.setForeground(new java.awt.Color(255, 255, 255));
        lbContador.setText("20");

        javax.swing.GroupLayout panelContadorLayout = new javax.swing.GroupLayout(panelContador);
        panelContador.setLayout(panelContadorLayout);
        panelContadorLayout.setHorizontalGroup(
            panelContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContadorLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(lbContador, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        panelContadorLayout.setVerticalGroup(
            panelContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbContador, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPregunta.setBackground(new java.awt.Color(255, 255, 255));
        panelPregunta.setRoundBottomLeft(60);
        panelPregunta.setRoundBottomRight(60);
        panelPregunta.setRoundTopLeft(60);
        panelPregunta.setRoundTopRight(60);

        lbPregunta.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbPregunta.setForeground(new java.awt.Color(238, 66, 102));
        lbPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPregunta.setText("La pregunta debería de ir en toda esta linea");

        javax.swing.GroupLayout panelPreguntaLayout = new javax.swing.GroupLayout(panelPregunta);
        panelPregunta.setLayout(panelPreguntaLayout);
        panelPreguntaLayout.setHorizontalGroup(
            panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelPreguntaLayout.setVerticalGroup(
            panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelOpcion1.setBackground(new java.awt.Color(255, 210, 63));
        panelOpcion1.setRoundBottomLeft(60);
        panelOpcion1.setRoundBottomRight(60);
        panelOpcion1.setRoundTopLeft(60);
        panelOpcion1.setRoundTopRight(60);

        btnOpcionA.setBackground(new java.awt.Color(0, 0, 0));
        btnOpcionA.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnOpcionA.setForeground(new java.awt.Color(255, 102, 0));
        btnOpcionA.setText("Opción A");
        btnOpcionA.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnOpcionA.setContentAreaFilled(false);
        btnOpcionA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOpcionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionAbtnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcion1Layout = new javax.swing.GroupLayout(panelOpcion1);
        panelOpcion1.setLayout(panelOpcion1Layout);
        panelOpcion1Layout.setHorizontalGroup(
            panelOpcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcion1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(btnOpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelOpcion1Layout.setVerticalGroup(
            panelOpcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcion1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnOpcionA)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelPuntos.setBackground(new java.awt.Color(238, 66, 102));
        panelPuntos.setRoundBottomRight(60);
        panelPuntos.setRoundTopRight(60);

        lbPuntos.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lbPuntos.setForeground(new java.awt.Color(255, 255, 255));
        lbPuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPuntos.setText("Pts 0");

        javax.swing.GroupLayout panelPuntosLayout = new javax.swing.GroupLayout(panelPuntos);
        panelPuntos.setLayout(panelPuntosLayout);
        panelPuntosLayout.setHorizontalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPuntos, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );
        panelPuntosLayout.setVerticalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPuntos, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOpcion2.setBackground(new java.awt.Color(255, 210, 63));
        panelOpcion2.setRoundBottomLeft(60);
        panelOpcion2.setRoundBottomRight(60);
        panelOpcion2.setRoundTopLeft(60);
        panelOpcion2.setRoundTopRight(60);

        btnOpcionB.setBackground(new java.awt.Color(0, 0, 0));
        btnOpcionB.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnOpcionB.setForeground(new java.awt.Color(255, 102, 0));
        btnOpcionB.setText("Opción B");
        btnOpcionB.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnOpcionB.setContentAreaFilled(false);
        btnOpcionB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOpcionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionBbtnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcion2Layout = new javax.swing.GroupLayout(panelOpcion2);
        panelOpcion2.setLayout(panelOpcion2Layout);
        panelOpcion2Layout.setHorizontalGroup(
            panelOpcion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcion2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(btnOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelOpcion2Layout.setVerticalGroup(
            panelOpcion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcion2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnOpcionB)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelOpcion3.setBackground(new java.awt.Color(255, 210, 63));
        panelOpcion3.setRoundBottomLeft(60);
        panelOpcion3.setRoundBottomRight(60);
        panelOpcion3.setRoundTopLeft(60);
        panelOpcion3.setRoundTopRight(60);

        btnOpcionC.setBackground(new java.awt.Color(0, 0, 0));
        btnOpcionC.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnOpcionC.setForeground(new java.awt.Color(255, 102, 0));
        btnOpcionC.setText("Opción C");
        btnOpcionC.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnOpcionC.setContentAreaFilled(false);
        btnOpcionC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOpcionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionCbtnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcion3Layout = new javax.swing.GroupLayout(panelOpcion3);
        panelOpcion3.setLayout(panelOpcion3Layout);
        panelOpcion3Layout.setHorizontalGroup(
            panelOpcion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcion3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(btnOpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelOpcion3Layout.setVerticalGroup(
            panelOpcion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcion3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnOpcionC)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelCategoria.setBackground(new java.awt.Color(238, 66, 102));
        panelCategoria.setRoundBottomLeft(60);
        panelCategoria.setRoundBottomRight(60);

        lbCategoria.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lbCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lbCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCategoria.setText("#1 Categoría");
        lbCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelCategoriaLayout = new javax.swing.GroupLayout(panelCategoria);
        panelCategoria.setLayout(panelCategoriaLayout);
        panelCategoriaLayout.setHorizontalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelCategoriaLayout.setVerticalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBtnSalir.setBackground(new java.awt.Color(238, 66, 102));
        panelBtnSalir.setRoundBottomLeft(60);
        panelBtnSalir.setRoundTopLeft(60);

        lbJugadorActual.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbJugadorActual.setForeground(new java.awt.Color(255, 255, 255));
        lbJugadorActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJugadorActual.setText("Jugador 1");

        javax.swing.GroupLayout panelBtnSalirLayout = new javax.swing.GroupLayout(panelBtnSalir);
        panelBtnSalir.setLayout(panelBtnSalirLayout);
        panelBtnSalirLayout.setHorizontalGroup(
            panelBtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnSalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbJugadorActual, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBtnSalirLayout.setVerticalGroup(
            panelBtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbJugadorActual, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBtnSalir1.setBackground(new java.awt.Color(255, 210, 63));
        panelBtnSalir1.setRoundBottomRight(60);
        panelBtnSalir1.setRoundTopRight(60);

        btnSalir1.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(204, 0, 51));
        btnSalir1.setText("Salir");
        btnSalir1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnSalir1.setContentAreaFilled(false);
        btnSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnSalir1Layout = new javax.swing.GroupLayout(panelBtnSalir1);
        panelBtnSalir1.setLayout(panelBtnSalir1Layout);
        panelBtnSalir1Layout.setHorizontalGroup(
            panelBtnSalir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnSalir1Layout.createSequentialGroup()
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        panelBtnSalir1Layout.setVerticalGroup(
            panelBtnSalir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnSalir1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnSalir1)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                .addComponent(panelPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(panelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(panelContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addComponent(panelBtnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panelBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bgPanelLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(panelContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(panelPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelBtnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPreguntaText(String newText) {
    int maxCaracteres = 38;
    int contadorCaracteres = newText.length();

    if (contadorCaracteres > maxCaracteres) {
        String textoReducido = newText.substring(0, contadorCaracteres); // Obtiene los primeros maxCaracteres caracteres
        lbPregunta.setText(textoReducido);
        // Ajusta el tamaño de la fuente aquí
        lbPregunta.setFont(new Font("Arial", Font.PLAIN, 14)); // Cambia el tamaño de la fuente según sea necesario
    } else {
        lbPregunta.setText(newText);
        // Restablece el tamaño de la fuente a su valor predeterminado
        lbPregunta.setFont(new Font("Arial", Font.PLAIN, 16)); // Tamaño de fuente predeterminado
    }
}
    
    public void setCategoriaText(String newText) {
        lbCategoria.setText(newText);
    }
  
    public void setbtnAText(String newText) {
        btnOpcionA.setText(newText);
    }   
      
    public void setbtnBText(String newText) {
        btnOpcionB.setText(newText);
    }
    
    public void setbtnCText(String newText) {
        btnOpcionC.setText(newText);
    }
    
    
    private void btnOpcionAbtnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionAbtnJugarActionPerformed
        this.respuesta = 1;
    }//GEN-LAST:event_btnOpcionAbtnJugarActionPerformed

    private void btnOpcionBbtnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionBbtnJugarActionPerformed
        this.respuesta = 2;
    }//GEN-LAST:event_btnOpcionBbtnJugarActionPerformed

    private void btnOpcionCbtnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionCbtnJugarActionPerformed
        this.respuesta = 3;     
    }//GEN-LAST:event_btnOpcionCbtnJugarActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
       this.setVisible(false);
       Jmenu menu = new Jmenu();
       menu.setVisible(true);
    }//GEN-LAST:event_btnSalir1ActionPerformed
public void setContadorText(String newText) {
    lbContador.setText(newText);
    lbContador.setFont(new Font("Arial", Font.PLAIN, 49)); // Tamaño de fuente predeterminado
    }
public void actualizarPuntos(int nuevosPuntos) {
    lbPuntos.setText("Pts " + nuevosPuntos);
    }
public void actualizarJugador(String jugador) {
    lbJugadorActual.setText(jugador);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMultijugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMultijugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMultijugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMultijugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMultijugador().setVisible(true);
            }
        });
    }
    
    public void cambiarColorPanelRespuesta(Byte numPanel, boolean esCorrecta) {
    PanelRound panelSeleccionado;
    switch (numPanel) {
        case 1: panelSeleccionado = panelOpcion1; break;
        case 2: panelSeleccionado = panelOpcion2; break;
        case 3: panelSeleccionado = panelOpcion3; break;
        default: return; // Si el número del panel no es válido, no hace nada
    }
    // Cambia el color del panel según si la respuesta es correcta o no
    panelSeleccionado.setBackground(esCorrecta ? Color.GREEN : Color.RED);
}

public void restablecerColorPanelRespuesta(Byte numPanel) {
    PanelRound panelSeleccionado;
    Color colorOriginal = new Color(255, 210, 63);
    switch (numPanel) {
        case 1: panelSeleccionado = panelOpcion1; break;
        case 2: panelSeleccionado = panelOpcion2; break;
        case 3: panelSeleccionado = panelOpcion3; break;
        default: return;
    }
    panelSeleccionado.setBackground(colorOriginal);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton btnOpcionA;
    private javax.swing.JButton btnOpcionB;
    private javax.swing.JButton btnOpcionC;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbContador;
    private javax.swing.JLabel lbJugadorActual;
    private javax.swing.JLabel lbPregunta;
    private javax.swing.JLabel lbPuntos;
    private com.poo.triviaquirk.PanelRound panelBtnSalir;
    private com.poo.triviaquirk.PanelRound panelBtnSalir1;
    private com.poo.triviaquirk.PanelRound panelCategoria;
    private com.poo.triviaquirk.PanelRound panelContador;
    private com.poo.triviaquirk.PanelRound panelOpcion1;
    private com.poo.triviaquirk.PanelRound panelOpcion2;
    private com.poo.triviaquirk.PanelRound panelOpcion3;
    private com.poo.triviaquirk.PanelRound panelPregunta;
    private com.poo.triviaquirk.PanelRound panelPuntos;
    // End of variables declaration//GEN-END:variables
/**
 * Retrieves the response value.
 *
 * This method returns the response value associated with the current instance.
 * The response value is of type Byte.
 *
 * @return The response value as a Byte.
 */
    public Byte getRespuesta() {
        return this.respuesta;
    }
}
